### ISSUE TITLE
Enumerated lists not escaped

### ISSUE THREAD

**Issue by retorquere** [kemitchell/markdown-escape.js#1]
The string `1. We're #1!"` is escaped to `1. We're \#1!`

**Comment by kemitchell** [comment]
Thanks for submitting an issue!

The regular expression for leading digits-dot is easy enough to add, but I wonder a bit about scope. Should the package also escape the dash in `"- We're #1!"`? I'm not sure.

I suppose we could call both `"."` and `"-"` Markdown "control characters", since they can be used to create block elements.

Might I ask what use case lead you to create this issue? Thanks!

**Comment by retorquere** [comment]
I write [Better BibTeX](https://github.com/ZotPlus/zotero-better-bibtex) and the [Atom plugin](https://atom.io/packages/zotero-citations) that uses it for scholarly markdown. It is a little unpredictable what I get back from the bibliography processor; I know I have seen a leading 1. at least once. Currently I do

```
      text = text.replace(/([-"\\`\*_{}\[\]\(\)#\+!])/g, "\\$1")
      text = text.replace(/(^|[\n])(\s*[0-9]+)\.(\s)/g, "$1\\.$2")
```
which seems to catch most, but I'm looking to use libraries where I can. I hadn't even thought about the leading dash; I'll have to add that.

**Comment by kemitchell** [comment]
Thanks for contributing to open source! My BibTex days are over, but once upon a time...

The scope question is still open. Should the function escape inline control characters only, or also assume it's receiving strings that are complete lines, and try to escape characters that create block elements as well. I don't think there's a clear convention.

If we go the "escaping block element markers" route, perhaps behind a flag:

- enumerated lists
- bullet point lists
- leading whitespace for code blocks
- fenced code block markers and info strings

And I think that list would keep growing.

**Comment by retorquere** [comment]
LaTeX forever :) I'd be inclined to answer "yes!" to all of those but in my use-case, code blocks don't happen.

**Comment by kemitchell** [comment]
Might you ...?:
1. Create a public markdown-block-escape repository under your own account
2. Accept a PR from me scaffolding a new package that wraps this one with additional, block-element escapes

I will further update this package to:
1. Reference your new markdown-block-escape
2. Clarify that this package does inline-element escapes only

**Comment by retorquere** [comment]
Ah, sure if that's your preference, but wouldn't a second parameter with options serve just as well? I'd prefer to have one well-developed module over multiple modules.

**Comment by kemitchell** [comment]
Plenty of room in the registry :wink:

An option flag would be functionally equivalent. But there are really two problems here:

1. how to escape inline-element control characters
2. how to escape block-element control characters

Those problems compose nicely: `2(1(input))`. And the input #2 expects is a superset of what #1 expects.

I fully expect there are inline-element use this cases this package doesn't cover yet. Hopefully Issues (like this one!) and my own work will help me find them over time. If I don't find them and update this package accordingly, they'll bite me in my own work. I'm motivated.

You're already thinking about block-level escaping for Better BibTeX. It's a problem you're motivated to solve.

I can't offer to maintain a block-level escape package long-term, but I'm happy to help you get one started today.
