### ISSUE TITLE
package url in github description is wrong

### ISSUE THREAD

**Issue by DetachHead** [kemitchell/markdown-escape.js#12]
![image](https://user-images.githubusercontent.com/57028336/202346882-395e592d-f197-451c-ad7f-f5a234e6eb46.png)

[https://www.npmjs.com/**packages**/markdown-escape](https://www.npmjs.com/packages/markdown-escape) is a 404. the correct url is [https://www.npmjs.com/**package**/markdown-escape](https://www.npmjs.com/package/markdown-escape)

**Comment by kemitchell** [comment]
Thanks. Fixed.
