### ISSUE TITLE
Does not escape table delimiters `|`

### ISSUE THREAD

**Issue by voxpelli** [kemitchell/markdown-escape.js#13]
Using this method on a string does not make it safe to include in a table cell using the table syntax

**Comment by kemitchell** [comment]
Neither original Gruber Markdown nor newer, standard CommonMark support pipe table syntax. That's a non-standard extension.

**Comment by voxpelli** [comment]
@kemitchell Maybe state that in he README? That its just the original core Markdown syntax and not any of the GitHub Formatted Markdown syntax that gets escaped?

The phrase `Markdown` often gets interpreted as GitHub Formatted Markdown nowadays
