### ISSUE TITLE
algorithm needs refining, escaping is not that simple as it being assumed currently

### ISSUE THREAD

**Issue by revelt** [kemitchell/markdown-escape.js#3]
hi all,

Currently, the algorithm will escape every single square bracket.

I believe this is flawed algorithm because it's not that simple. Also, currently, the output of "escaped" string, output of this library makes markdown parsers `throw`.

Here's an example. Take a string:

```
Sort natural number index ranges [ [5, 6], [1, 3] ] => [ [1, 3], [5, 6] ]
```

This library will escape every left square bracket:
https://runkit.com/embed/561ymjsqs6cu

```
Sort natural number index ranges \[ \[5, 6\], \[1, 3\] \] =&gt; \[ \[1, 3\], \[5, 6\] \]
```

This "escaped" output breaks the parser of Atom Markdown preview plugin [markdown-preview-enhanced](https://atom.io/packages/markdown-preview-enhanced):

<img width="473" alt="screen shot 2017-11-29 at 16 43 18" src="https://user-images.githubusercontent.com/8344688/33387174-7ca471d0-d524-11e7-9e8a-bbef85b0e296.png">

---

Now, since Atom has the Markdown syntax and will try to colour the `.md` files, we can backwards-engineer what level of escaping would suffice. Apparently, two rules can be extracted from that:

1. Left bracket followed by space is not considered a "link" bracket any more. Observe the bracket that follows word "ranges".
2. If we consider `[5, 6]`, it's enough to escape only the left, opening bracket. It seems syntax Markdown parser will not misinterpret right-side square brackets if they don't have unescaped left-side counterparts.

I might be wrong, but so far it seems the following level of escaping is enough to satisfy both Atom MD Syntax and `markdown-preview-enhanced` parsers:

```
Sort natural number index ranges [ \[5, 6], \[1, 3] ] => [ \[1, 3], \[5, 6] ]
```

I would suggest to cross-check various other popular MD API's that parse the text. Those should not `throw` when consuming escaped output of this library.

**Comment by marko-knoebl** [comment]
Well, I think it's definitely *valid* to escape every square bracket.

If a parser *throws* on this syntax I think the parser is wrong.

According to the CommonMark spec: "Any sequence of characters is a valid CommonMark document." So a Markdown parser that parses CommonMark should never throw

https://spec.commonmark.org/0.29/#preliminaries

**Comment by kemitchell** [comment]
I'm definitely open to the idea that there are problems with this package. But I do believe I followed the CommonMark spec about escapes. @revelt, perhaps you'd like to find out which parser is creating the error you're seeing, and send them your example, as escaped, as a bug report?
